package render

import (
	"fmt"
	"sort"

	cfg "github.com/Sharper-Flow/Opencode-Advance/internal/config"
	"gopkg.in/yaml.v3"
)

type visionServerYAML struct {
	Port                  int                 `yaml:"port,omitempty"`
	Transport             string              `yaml:"transport,omitempty"`
	Command               string              `yaml:"command,omitempty"`
	Args                  []string            `yaml:"args,omitempty"`
	Env                   map[string]string   `yaml:"env,omitempty"`
	URL                   string              `yaml:"url,omitempty"`
	Headers               map[string]string   `yaml:"headers,omitempty"`
	Autostart             bool                `yaml:"autostart,omitempty"`
	RestartPolicy         string              `yaml:"restart_policy,omitempty"`
	MaxRestarts           int                 `yaml:"max_restarts,omitempty"`
	Stateful              bool                `yaml:"stateful,omitempty"`
	AvailabilityProfile   string              `yaml:"availability_profile,omitempty"`
	SessionTimeout        string              `yaml:"session_timeout,omitempty"`
	MaxSessions           int                 `yaml:"max_sessions,omitempty"`
	SessionTTL            string              `yaml:"session_ttl,omitempty"`
	HealthCheckInterval   string              `yaml:"health_check_interval,omitempty"`
	RequestTimeout        string              `yaml:"request_timeout,omitempty"`
	Retry                 *cfg.RetryConfig    `yaml:"retry,omitempty"`
	CircuitBreaker        *cfg.CircuitBreaker `yaml:"circuit_breaker,omitempty"`
	SharedReadOnlyTools   []string            `yaml:"shared_read_only_tools,omitempty"`
	SharedResultCacheTTL  string              `yaml:"shared_result_cache_ttl,omitempty"`
	SharedResultCacheSize int                 `yaml:"shared_result_cache_size,omitempty"`
	MaxInFlightRequests   int                 `yaml:"max_in_flight_requests,omitempty"`
	Required              bool                `yaml:"required,omitempty"`
	Source                string              `yaml:"source,omitempty"`
	Description           string              `yaml:"description,omitempty"`
}

// slotGroupYAML is the Vision servers.yaml serialization shape for a slot
// group declaration. Mirrors Vision's internal/config.SlotGroupConfig
// field-for-field. OCA never expands per-slot servers — Vision performs
// expansion at load time.
type slotGroupYAML struct {
	Template  string     `yaml:"template"`
	BasePort  int        `yaml:"base_port"`
	Count     int        `yaml:"count"`
	GroupPort int        `yaml:"group_port"`
	Defaults  *yaml.Node `yaml:"defaults,omitempty"`
}

// RenderVisionServers renders full vision/servers.yaml. daemon-type servers are skipped.
func RenderVisionServers(stack *cfg.Stack, sourcePath string) ([]byte, error) {
	root := &yaml.Node{Kind: yaml.MappingNode}
	serversNode := &yaml.Node{Kind: yaml.MappingNode}
	root.Content = append(root.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: "servers"},
		serversNode,
	)

	names := make([]string, 0, len(stack.MCP.Servers))
	for name := range stack.MCP.Servers {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		s := stack.MCP.Servers[name]
		if s.Type == "daemon" {
			continue
		}
		node, err := serverNode(s)
		if err != nil {
			return nil, err
		}
		serversNode.Content = append(serversNode.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: name},
			node,
		)
	}

	if len(stack.MCP.SlotGroups) > 0 {
		groupsNode := &yaml.Node{Kind: yaml.MappingNode}
		groupNames := make([]string, 0, len(stack.MCP.SlotGroups))
		for name := range stack.MCP.SlotGroups {
			groupNames = append(groupNames, name)
		}
		sort.Strings(groupNames)
		for _, name := range groupNames {
			g := stack.MCP.SlotGroups[name]
			node, err := slotGroupNode(g)
			if err != nil {
				return nil, err
			}
			groupsNode.Content = append(groupsNode.Content,
				&yaml.Node{Kind: yaml.ScalarNode, Value: name},
				node,
			)
		}
		root.Content = append(root.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: "slot_groups"},
			groupsNode,
		)
	}

	b, err := yaml.Marshal(root)
	if err != nil {
		return nil, err
	}
	header := fmt.Sprintf("# vision/servers.yaml — generated by oca apply\n# source: %s\n\n", sourcePath)
	return append([]byte(header), b...), nil
}

func serverNode(s cfg.Server) (*yaml.Node, error) {
	timeout := s.RequestTimeout
	if timeout == "" && s.Timeout > 0 {
		timeout = fmt.Sprintf("%dms", s.Timeout)
	}
	transport := ""
	if s.Transport != "" {
		transport = s.Transport
	} else if s.Type != "" && s.Type != "daemon" {
		transport = s.Type
	}
	v := visionServerYAML{
		Port:                  s.Port,
		Transport:             transport,
		Command:               s.Command,
		Args:                  s.Args,
		Env:                   s.Env,
		URL:                   s.URL,
		Headers:               s.Headers,
		Autostart:             s.Autostart,
		RestartPolicy:         s.RestartPolicy,
		MaxRestarts:           s.MaxRestarts,
		Stateful:              s.Stateful,
		AvailabilityProfile:   s.AvailabilityProfile,
		SessionTimeout:        s.SessionTimeout,
		MaxSessions:           s.MaxSessions,
		SessionTTL:            s.SessionTTL,
		HealthCheckInterval:   s.HealthCheckInterval,
		RequestTimeout:        timeout,
		Retry:                 s.Retry,
		CircuitBreaker:        s.CircuitBreaker,
		SharedReadOnlyTools:   s.SharedReadOnlyTools,
		SharedResultCacheTTL:  s.SharedResultCacheTTL,
		SharedResultCacheSize: s.SharedResultCacheSize,
		MaxInFlightRequests:   s.MaxInFlightRequests,
		Required:              s.Required,
		Source:                s.Source,
		Description:           s.Description,
	}
	b, err := yaml.Marshal(v)
	if err != nil {
		return nil, err
	}
	var node yaml.Node
	if err := yaml.Unmarshal(b, &node); err != nil {
		return nil, err
	}
	if len(node.Content) == 0 {
		return &yaml.Node{Kind: yaml.MappingNode}, nil
	}
	return node.Content[0], nil
}

// slotGroupNode converts a SlotGroup into a yaml.Node suitable for use
// under a servers.yaml `slot_groups:` mapping. Defaults serialize via
// serverNode so all ServerConfig fields ride through.
func slotGroupNode(g cfg.SlotGroup) (*yaml.Node, error) {
	var defaultsNode *yaml.Node
	if g.Defaults != nil {
		node, err := serverNode(*g.Defaults)
		if err != nil {
			return nil, err
		}
		defaultsNode = node
	}
	v := slotGroupYAML{
		Template:  g.Template,
		BasePort:  g.BasePort,
		Count:     g.Count,
		GroupPort: g.GroupPort,
		Defaults:  defaultsNode,
	}
	b, err := yaml.Marshal(v)
	if err != nil {
		return nil, err
	}
	var node yaml.Node
	if err := yaml.Unmarshal(b, &node); err != nil {
		return nil, err
	}
	if len(node.Content) == 0 {
		return &yaml.Node{Kind: yaml.MappingNode}, nil
	}
	return node.Content[0], nil
}
